function Head = file_GetNewHead()
%----------------------------------------------------------
% Create New Head
%
% Head   : Data Header
%
% Author : Gwan-Taek Lee
% Last update : 2012. 02. 03.
%----------------------------------------------------------

    Head = struct(...
            'FileType',  [],...
            'FileName',  [],...
            'FilePath',  [],...
            'StartDate', [],...
            'StartTime', [],...
            'ChanNum',   [],...
            'ChanLabel', [],...
            'DataChan',  [],...
            'RefeChan',  [],...
            'EvntChan',  [],...
            'ResvChan',  [],...
            'PhysDim',   [],...
            'SampRate',  [],...
            'TimeNum',   [],...
            'Filter',    [],...
            'Freq',      [],...
            'Event',     [],...
            'Stage',     []);
              
end